# Generated by Django 5.2.10 on 2026-01-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('duration', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('pricing', models.CharField(choices=[('full', 'Full Price'), ('concession', 'Concession')], max_length=20)),
                ('payment', models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('simulated', 'Simulated Payment')], max_length=20)),
                ('membership', models.CharField(choices=[('basic', 'Basic – £9.99/month'), ('pro', 'Pro – £19.99/month'), ('elite', 'Elite – £29.99/month')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
